    .include "zeropage.inc65"

    .zeropage

sp:               .res 2
sreg:             .res 2
regsave:          .res 4
ptr1:             .res 2
ptr2:             .res 2
ptr3:             .res 2
ptr4:             .res 2
tmp1:             .res 1
tmp2:             .res 1
tmp3:             .res 1
tmp4:             .res 1
tmpstack:         .res 1
VDP_PATTERN_INIT:       .res 1
VDP_PATTERN_INIT_HI:    .res 1
DISPLAY_PTR:      .res 1
DISPLAY_PTR_HI:   .res 1
R0:               .word 0
